language: ruby
rvm:
- 3.0.6
before_install:
  - gem update --system
  - gem install bundler
install: 
- bundle install
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true